### ISSUE TITLE
Mob Sound Localisation

### ISSUE THREAD

**Issue by Atlantispy** [nekomaster1000/Infernal-Expansion#416] opened 2023-01-25 17:37 UTC
### Describe the Bug

The sound played by the mobs in the mod seems to originate from the player rather than the mob, not sure if this is being exacerbated by the Sound Physics mod but the Basalt Giant and Shroomloin sound are especially are overpowering.

### Reproduction Steps

1. Launch 1.18.2 Forge with Infernal Expansion and Sound Physics Remastered installed.
2. Enter the Nether
3. Locate Shroomloin or Basalt Giant

### Expected Result

Sound to be locationally originating from the mob.

### Operating System

Windows 10

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Other Mods

No crash, but it's a kitchen sink mod pack.

I believe that Creatures and Beasts had a similar issue that was recently fixed.

**Comment by Dariensg** [comment] 2023-01-25 20:15
Duplicate of #406

**Closed as completed by Dariensg** 2023-01-25 20:15 UTC
Labels: bug, duplicate
