### ISSUE TITLE
Warp Beetles spawn in overworld

### ISSUE THREAD

**Issue by ghost** [nekomaster1000/Infernal-Expansion#16] opened 2021-01-22 10:56 UTC
I dont think they are supposed to

**Comment by caelwarner** [comment] 2021-01-23 03:50
Is there any way to reproduce this error? And are they spawning in a specific biome? Anymore details would be much appreciated so we can look into this issue.

**Comment by ghost** [comment] 2021-01-23 04:55
Im not sure I think I have it set to default settings, they just appear in my overworld - Didn't know it was a bug til I tried changing the config to keep them in the nether to find they were never supposed to be in the overworld to begin with xD

**Comment by ghost** [comment] 2021-01-23 04:56
I will check which biome I am in where they appear when I can - Not sure if I seen them in multiple biomes or just the one where I have a base

**Comment by ghost** [comment] 2021-01-23 05:22
The biome I am sure it spawns in in the overworld is BYG (biomes you'll go) : deciduous_clearing

also to add more details, no other mobs from this mod spawn in overworld, and I have seen at least one mob from the mod in the nether (but no beetles there that Ive seen yet)

**Comment by caelwarner** [comment] 2021-03-13 08:04
I could not recreate this error, maybe it was caused by another mod (if you have other mods installed), or maybe it has since been fixed in updates to Infernal Expansion and BYG

If you have anything else to add, please do so, if not I will be closing this issue soon,
Thanks

**Closed as completed** 2021-03-14 19:35 UTC
Labels: bug
