### ISSUE TITLE
[2.2.0] Broken recipes for Polished Basalt Vertical Slab & Basalt Bricks Vertical Slab

### ISSUE THREAD

**Issue by Thombias** [nekomaster1000/Infernal-Expansion#263] opened 2021-08-15 17:11 UTC
**Describe the Bug:**
Polished Basalt Vertical Slab can't be crafted in the crafting table due to a typo. The item ID is supposed to be 'infernalexp:polished_basalt_slab' The letter h in polished is missing and therefore the crafting recipe doesn't work.

Basalt Bricks Vertical Slab can't be crafted in the Stonecutter because the recipe has no output.

I double-checked with JEI and it doesn't show the recipes for those 2 mentioned blocks.

**How to Reproduce:**
Install this mod and start Minecraft with the game output log. Once you load a world you get the following 2 error messages down below.

**Expected Behavior:**
Is there really an explanation necessary?

**Screenshots:**

![image](https://user-images.githubusercontent.com/46842890/129486321-ddd82d19-b210-4c4b-a21f-79d06034d942.png)

![image](https://user-images.githubusercontent.com/46842890/129486307-db8c2e57-18c3-45be-88f7-2416f3eadee4.png)

**Version Information:**
 - Operating System: Windows 10 Pro
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.0.2
 - Other mods that were running when the crash happened: No crash

**Additional Context:**
In case the images don't work here are the error messages from the log output:

Parsing error loading recipe infernalexp:crafting/crafting_shaped/polished_basalt_vertical_slab
com.google.gson.JsonSyntaxException: Unknown item 'infernalexp:polised_basalt_slab'

Recipe has no output. Infernal Expansion infernalexp:stonecutting/basalt_bricks_vertical_slab class net.minecraft.item.crafting.StonecuttingRecipe
Outputs:
net.minecraft.item.ItemStack: [[2 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 basalt_bricks infernalexp:basalt_bricks]]

**Comment by caelwarner** [comment] 2021-08-15 17:40
Duplicate of #260

**Closed as completed by caelwarner** 2021-08-15 17:40 UTC
Labels: bug, duplicate
