### ISSUE TITLE
[Bug/Crash] World Creation Crash 

### ISSUE THREAD

**Issue by ZilverLazarus** [nekomaster1000/Infernal-Expansion#268] opened 2021-08-26 07:32 UTC
**Describe the Bug:**
After launching the game, loading into an existing world (or creating a new world and loading into it), leaving the world, and trying to create a new world, the game crashes.

**How to Reproduce:**
1). Load into an existing world / create a new world and load into it
2). Exit world
3). Try creating a new world
4). Crash

**Expected Behavior:**
New world gets created without issue/crash.

**Screenshots:**
I don't have screenshots, but I do have a crash log that lists Infernal Expansion in the stacktrace.
[crash-2021-08-26_03.16.51-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/7052425/crash-2021-08-26_03.16.51-client.txt)

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.1.1
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.32
 - Other mods that were running when the crash happened:
[Listed in the crash report sent above]

**Additional Context:**
There is a high chance that this is an incompatibility with Enhanced Celestials 2.0.6 for whatever reason. I'm fairly certain that it was the only mod changed between tests that caused this result.

**Comment by SwanX1** [comment] 2021-08-26 08:09
Duplicate of #258

**Closed as completed** 2021-08-26 08:09 UTC
Labels: bug, duplicate
