### ISSUE TITLE
Feature placement crashed

### ISSUE THREAD

**Issue by ddship12** [nekomaster1000/Infernal-Expansion#314] opened 2021-11-18 04:30 UTC
**Version Information:**
 - Operating System: windows 10
 - Mod Version: 2.4.0 1.17x
 - Minecraft Version: 1.17.1
 - Forge Version: 37.0.104

**Additional Context:**
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 18/11/2021, 10:47 am
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(SourceFile:58) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(SourceFile:91) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(SourceFile:146) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(SourceFile:102) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
Caused by: net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$18(ChunkMap.java:529) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2337!:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:515) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?] {}
	... 11 more
Caused by: java.lang.IllegalStateException: Tag infernalexp:planted_quartz_base_blocks used before it was bound
	at net.minecraft.tags.StaticTagHelper$Wrapper.m_13263_(StaticTagHelper.java:142) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.tags.StaticTagHelper$Wrapper.m_8110_(StaticTagHelper.java:153) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at org.infernalstudios.infernalexp.blocks.PlantedQuartzBlock.isValidGround(PlantedQuartzBlock.java:52) ~[infernal-expansion-1.17.1-2.4.0.jar%2356!:2.4.0] {re:classloading}
	at org.infernalstudios.infernalexp.blocks.PlantedQuartzBlock.canAttachToSurface(PlantedQuartzBlock.java:90) ~[infernal-expansion-1.17.1-2.4.0.jar%2356!:2.4.0] {re:classloading}
	at org.infernalstudios.infernalexp.blocks.PlantedQuartzBlock.m_7898_(PlantedQuartzBlock.java:85) ~[infernal-expansion-1.17.1-2.4.0.jar%2356!:2.4.0] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60710_(BlockBehaviour.java:685) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at org.infernalstudios.infernalexp.world.gen.features.PlantedQuartzFeature.m_142674_(PlantedQuartzFeature.java:54) ~[infernal-expansion-1.17.1-2.4.0.jar%2356!:2.4.0] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(SourceFile:58) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.DecoratedFeature.m_159537_(SourceFile:29) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] {}
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.levelgen.feature.DecoratedFeature.m_142674_(SourceFile:28) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(SourceFile:58) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.level.biome.Biome.m_47484_(Biome.java:266) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:BiomeMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_7399_(SourceFile:245) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_156252_(ChunkStatus.java:87) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_156212_(ChunkStatus.java:208) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$18(ChunkMap.java:517) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2337!:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:515) ~[client-1.17.1-20210706.113038-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?] {}
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 551231008 bytes (525 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c8d
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x591b
	Graphics card #1 versionInfo: DriverVersion=30.0.100.9684
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16372.39
	Virtual memory used (MB): 13956.70
	Swap memory total (MB): 8264.02
	Swap memory used (MB): 1008.97
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 1 / 8; [ServerPlayer['ddship'/79, l='ServerLevel[First Anicent RPG]', x=248.27, y=33.33, z=-176.95]]
	Data Packs: vanilla, mod:more_stones_2 (incompatible), mod:blue_skies (incompatible), mod:bigger_caves (incompatible), mod:infernalexp (incompatible), mod:villagerspillagers (incompatible), mod:jei, mod:forge, mod:twilightforest, mod:extragems, mod:structure_gel (incompatible), mod:journeymap (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		MoreStones+II+v1.30+(1.17.1).jar                  |More Stones II                |more_stones_2                 |1.30                |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.17.1-1.2.1.jar                       |Blue Skies                    |blue_skies                    |1.2.1               |DONE      |Manifest: NOSIGNATURE
		Bigger-Caves-1.17.1-v1.0.jar                      |Example Mod                   |bigger_caves                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.104-universal.jar               |Forge                         |forge                         |37.0.104            |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		twilightforest-1.17.1-4.0.829-universal.jar       |The Twilight Forest           |twilightforest                |4.0.829             |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-1.17.1-2.4.0.jar               |Infernal Expansion            |infernalexp                   |2.4.0               |DONE      |Manifest: NOSIGNATURE
		Pillage+the+Village+1.3.jar                       |Pillage the Village           |villagerspillagers            |1.3                 |DONE      |Manifest: NOSIGNATURE
		ExtraGems-1.17.1-(v.2.0.4).jar                    |ExtraGems                     |extragems                     |2.0.4               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.17.1-2.0.1.jar                    |Structure Gel API             |structure_gel                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.17.1-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.2.0.35.jar                           |Just Enough Items             |jei                           |8.2.0.35            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 46c9c30c-bf80-4964-ae2b-302304ad089c
	FML: 37.0
	Forge: net.minecraftforge:37.0.104
```

**Comment by caelwarner** [comment] 2022-06-18 19:36
Duplicate of #310. Likely caused by Blue Skies which is present in both crashes and has a mixin into `ConfiguredFeature`

**Closed as completed** 2023-02-17 21:00 UTC
Labels: bug, duplicate, 1.17
