### ISSUE TITLE
Unable to load structures with /place or structure blocks

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [nekomaster1000/Infernal-Expansion#389] opened 2022-09-25 14:00 UTC
### Describe the Bug

Unable to load structures with /place or structure blocks, able to do so with vanilla structures

### Reproduction Steps

1.Use /place structure infernalexp:[insert any structure name here]
OR
1.Place a structure block, set to "load", then input infernalexp:[insert any structure name here]

### Expected Result

Structure exists

### Operating System

Windows 10

### Mod Version

2.5.3

### Minecraft Version

1.19

### Forge Version

1.19.2-43.1.27

**Comment by Bonniethebunny-hub** [comment] 2022-09-25 14:02
WAIT FUCK ITS /place

**Comment by Bonniethebunny-hub** [comment] 2022-09-25 14:02
Still doesnt work though

**Comment by caelwarner** [comment] 2023-02-18 06:41
For the /place command everything is working as intended. Infernal Expansions structures are kinda picky with where they choose to spawn. They need a large enough and flat enough space to be able to spawn on. If the space you're currently trying to spawn a structure in doesn't meet these requirements it will fail spawning it. 

As for the structure block, it expects a resource location to an NBT file, not a resource location to a structure. An example would be `infernalexp:glowstone_canyon/heaven_4`. You can see all the IE NBT files here https://github.com/infernalstudios/Infernal-Expansion/tree/1.18/src/main/resources/data/infernalexp/structures.

I'm going to close this issue now. If you want more help please just re-open it.

**Closed as completed by caelwarner** 2023-02-18 06:41 UTC
Labels: bug
