### ISSUE TITLE
WorldSettingsImport Error Spam and Server Lag

### ISSUE THREAD

**Issue by Hexadiagonal** [nekomaster1000/Infernal-Expansion#286] opened 2021-09-14 17:50 UTC
**Describe the Bug:**
[Server thread/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Base value out of range: 256 [-10-128]

Server spam in console, correlated with severe lag and rubber banding approx. every couple of minutes. I have confirmed that removal of Infernal Expansion removes the recurring error and lag.

**How to Reproduce:**

https://github.com/infernalexp/Infernal-Expansion/issues/261

I see that there is a link here, with one contributor providing a fix that ostensibly fixes these mod interactions:
 https://github.com/infernalexp/Infernal-Expansion/blob/0df577b872303e508a4dff270a47390584396d52/src/main/java/org/infernalstudios/infernalexp/mixin/common/MixinChunkGenerator.java#L29-L32

I have the latest version, so I am not sure what I am missing yet.

**Version Information:**
 - Operating System: Win 10 x64
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Other mods that were running when the crash happened:

**Additional Context:**

I am running Valhelsia's mods, along with Endergetic Expansion, Abnormals Core, etc. All associated with this issue. Please let me know if you need an exhaustive list.

**Comment by SwanX1** [comment] 2021-09-14 18:35
If it's a duplicate, don't report it. (you literally linked the issue?)
Duplicate of #261

**Closed as completed by SwanX1** 2021-09-14 18:35 UTC
Labels: bug, duplicate

**Comment by Hexadiagonal** [comment] 2021-09-14 18:50
> If it's a duplicate, don't report it. (you literally linked the issue?)
> Duplicate of #261

Hey, sorry. I'm trying to understand if the issue is resolved. I'm pretty new to using GitHub in any collaborative sense, and I can understand frustration with getting duped problems. Definitely my bad, just don't forget sometimes you're just working with someone who's getting used to something new.

**Comment by SwanX1** [comment] 2021-09-14 18:51
It's fixed, the fix isn't published on curseforge/modrinth yet.

**Comment by Hexadiagonal** [comment] 2021-09-14 18:51
Thanks for the clarification. I misread the info and thought it had persisted into the current versions. Thanks for your patience.
