### ISSUE TITLE
Biome 	Failure message: Infernal Expansion (infernalexp) has failed to load correctly 		java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by Jetpack-Cat** [nekomaster1000/Infernal-Expansion#386] opened 2022-09-12 23:54 UTC
### Describe the Bug

Crash when starting the game. I'm getting this report more and more lately.
https://gist.github.com/Jetpack-Cat/6d4a9862251d0ab70fe5a484f65dc634

![image](https://user-images.githubusercontent.com/100042170/189777259-00e39fab-03e3-4cf6-96ca-d3aba63c42f0.png)

### Reproduction Steps

1. Start game, randomly crash.

### Expected Result

Not to crash

### Operating System

Windows 11

### Mod Version

2.5.0

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Other Mods

https://www.curseforge.com/minecraft/modpacks/jetpack-cat/relations/dependencies

**Comment by Dariensg** [comment] 2022-09-13 00:20
Interesting... According to that, Forge itself is failing... I'll talk to the team and see what we can figure out

**Comment by caelwarner** [comment] 2023-02-18 20:51
Duplicate of #401, #405

**Closed as completed by caelwarner** 2023-02-18 20:51 UTC
Labels: bug
