### ISSUE TITLE
Polished Basalt Vertical Slab Parsing error

### ISSUE THREAD

**Issue by IdealIdeas** [nekomaster1000/Infernal-Expansion#285] opened 2021-09-13 22:47 UTC
**Describe the Bug:**
[13Sep2021 13:50:41.227] [Worker-Main9/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe infernalexp:crafting/crafting_shaped/polished_basalt_vertical_slab
com.google.gson.JsonSyntaxException: Unknown item 'infernalexp:polised_basalt_slab'

**How to Reproduce:**
install mod

**Expected Behavior:**
no errors

**Screenshots:**

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: Current 1.16.5 - 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened:

**Additional Context:**
No crash, just an error I seen.

**Comment by SwanX1** [comment] 2021-09-14 04:08
Duplicate of #260

**Closed as completed by SwanX1** 2021-09-14 04:08 UTC
Labels: bug, duplicate
