### ISSUE TITLE
Infernal Expansion, magma block entity is not compatible with and custom entity spawner of When Dundeons Arise

### ISSUE THREAD

**Issue by Jukabofy** [nekomaster1000/Infernal-Expansion#236] opened 2021-08-05 19:49 UTC
**Describe the Bug:**
Is a bug with the mod: When Dungeons Arise (https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise) in one of them structures
Is an spawner. Skeleton spawner on that ship
That has a magma slime riding it

**How to Reproduce:**
Well, in Discord, 
Kaleidio (Modpack dev) told me:
- might wanna bug report this to infernal expansion team.  it looks like their custom slimes do something bad with spawn/pathfinding code.
- I assumed the slime is somewhere they aren't able to see
either that or the mixin is so broken it crossed over into slime ai bytecode somehow
ah yea magma slime
infernal expansion is a nether mod so that's definitely what gone wrong here.  their magma slime override

**Expected Behavior:**
It just happen when I come close, and the spawners are activated, I mean, just happened with the entities

**Screenshots:**
The ISSUE START HERE at [10:12:06]
[10:01:59] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 16 msecs
[10:02:54] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Respawn point set
[10:03:46] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 414 advancements
[10:06:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:06:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:06:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:06:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:07:27] [Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container
[10:08:01] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 417 advancements
[10:11:47] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 417 advancements
[10:11:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:11:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:11:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:11:58] [Server thread/INFO] [co.si.sh.ut.cu.Utils/]: Saving config options on path: C:\Users\JUANCARLOS\AppData\Roaming\.minecraft\shrines-saves
[10:12:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.entity.ai.controller.MovementController cannot be cast to net.minecraft.entity.monster.SlimeEntity$MoveHelperController
	Index: 9
	Listeners:
		0: HIGHEST
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@9c63984 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		2: ASM: class org.orecruncher.lib.effects.EntityEffectHandler onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		3: NORMAL
		4: ASM: class com.maciej916.maenchants.common.subscribers.ForgeEventSubscriber onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		5: ASM: net.mcreator.comfortablenether.procedures.PiglinBruteAxeProcedure@7aa80202 onEntitySpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		6: ASM: class me.marnic.extrabows.common.events.ExtraBowsEventHandler arrowConstructing(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		7: ASM: com.github.alexthe666.citadel.server.CitadelEvents@40685f0 onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		8: ASM: com.nekomaster1000.infernalexp.events.MiscEvents@7dc680e8 onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		9: ASM: com.nekomaster1000.infernalexp.events.MobEvents@1fa8278e onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$2969/556272827@48ad8970
		11: ASM: class org.orecruncher.lib.service.ModuleServiceManager entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		12: ASM: INSTANCE onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		13: ASM: com.blackgear.cavesandcliffs.common.events.EntityGoalEvents@49bd2e8b onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		14: ASM: class com.legacy.dungeons_plus.DPEvents onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		15: ASM: class com.minecraftabnormals.savageandravage.core.other.SREvents onLivingSpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		16: ASM: class baguchan.hunterillager.event.EntityEvent addSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		17: ASM: com.baranhan.undefeatables.handlers.MobCreationHandler@2778d068 onSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		18: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@793f08d6 onLivingJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		19: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@669fdf1d entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		20: LOWEST
		21: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.EntityEvents onEntitySpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
java.lang.ClassCastException: net.minecraft.entity.ai.controller.MovementController cannot be cast to net.minecraft.entity.monster.SlimeEntity$MoveHelperController
	at com.nekomaster1000.infernalexp.entities.ai.AvoidBlockGoal.<init>(AvoidBlockGoal.java:34)
	at com.nekomaster1000.infernalexp.entities.ai.AvoidBlockGoal.<init>(AvoidBlockGoal.java:25)
	at com.nekomaster1000.infernalexp.events.MobEvents.onEntityJoin(MobEvents.java:169)
	at net.minecraftforge.eventbus.ASMEventHandler_289_MobEvents_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2579/1281045190.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813)
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754)
	at net.minecraft.world.IServerWorld$$Lambda$14555/222070795.accept(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$2147/1415108264.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11)
	at net.minecraft.world.server.ServerWorld.func_242106_g(ServerWorld.java:868)
	at net.minecraft.world.spawner.AbstractSpawner.func_98278_g(AbstractSpawner.java:144)
	at net.minecraft.tileentity.MobSpawnerTileEntity.func_73660_a(SourceFile:62)
	at net.minecraft.world.World.func_217391_K(World.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$12813/1291209693.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[10:12:07] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 2b7cd318-6154-4e6d-be5d-c48bee092632
[10:12:07] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$12813/1291209693.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Caused by: java.lang.ClassCastException: net.minecraft.entity.ai.controller.MovementController cannot be cast to net.minecraft.entity.monster.SlimeEntity$MoveHelperController
	at com.nekomaster1000.infernalexp.entities.ai.AvoidBlockGoal.<init>(AvoidBlockGoal.java:34) ~[?:2.0.0-beta.5] {re:classloading}
	at com.nekomaster1000.infernalexp.entities.ai.AvoidBlockGoal.<init>(AvoidBlockGoal.java:25) ~[?:2.0.0-beta.5] {re:classloading}
	at com.nekomaster1000.infernalexp.events.MobEvents.onEntityJoin(MobEvents.java:169) ~[?:2.0.0-beta.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_289_MobEvents_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2579/1281045190.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$14555/222070795.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$2147/1415108264.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld.func_242106_g(ServerWorld.java:868) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.spawner.AbstractSpawner.func_98278_g(AbstractSpawner.java:144) ~[?:?] {re:classloading}
	at net.minecraft.tileentity.MobSpawnerTileEntity.func_73660_a(SourceFile:62) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:A}
	... 6 more
AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (142 ms)
[Launcher] Minecraft closed with exit code: -1
[Launcher] Launcher exited.
flush now
flush now

**Version Information:**
Windows 10
(RAM)	8.00 GB
Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz, 1190 Mhz
Mod List: 
		TreeChop-1.16.4-0.14.4.jar 
		Ma-Enchants-1.16.5-3.6.0.jar
		infernal-expansion-2.0.0-beta.5.jar 
		Shrines-1.16.5-1.8.1.jar 
		PiratesAndLootersMotionUpdate.jar 
		jei-1.16.5-7.7.0.106.jar  
		ComfortableNether4.3.jar  
		abnormals_core-1.16.5-3.1.1.jar
		looot-1.16.4-1.0.0.3.jar     
		Undefeatables+1.4.jar   
		toadterror-1.16.4-1.0.0.jar    
		BetterCaves-Forge-1.16.4-1.1.2.jar   
		Waystones_1.16.5-7.6.2.jar       
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar 
		AdFinders-1.16.4-5.0.8.0-build.0115.jar    
		citadel-1.7.0-1.16.5.jar                         
		alexsmobs-1.11.1.jar                          
		YungsApi-1.16.4-Forge-11.jar         
		environmental-1.16.5-1.0.0.jar           
		champions-forge-1.16.5-2.0.1.7.jar     
		DungeonCrawl-1.16.3-2.2.4.jar           
		toolleveling-1.16.5-1.2.4.jar             
		u_team_core-1.16.5-3.2.0.194.jar       
		outvoted-1.16.5-1.2.4.jar           
		forge-1.16.5-36.1.0-universal.jar         
		NoIncreasingRepairCost-1.16.4-1.0.0.jar     
		meetyourfight-1.16.5-1.1.2.jar            
		DynamicSurroundings-1.16.4-4.0.4.2.jar     
		structure_gel-1.16.5-1.7.7.jar         
		DungeonsArise-1.16.5-2.1.45-release.jar      
		forge-1.16.5-36.1.0-client.jar       
		cavebiomes-2.0.jar                   
		upgrade_aquatic-1.16.5-3.1.0.jar        
		cofh_core-1.16.4-1.2.1.jar               
		endergetic-1.16.4-3.0.0.jar             
		useful_backpacks-1.16.5-1.12.0.88.jar      
		repurposed_structures-1.16.5-2.7.10-forge.jar  
		compactores-1.16.5-3.0.3.jar           
		practicaltools-1.16.3-1.8.jar          
		dungeons_plus-1.16.5-1.1.5.jar       
		towers_of_the_wild-1.16.4-2.0.1.jar    
		CavesAndCliffsBackport-6.1.jar         
		DungeonsEnhanced-1.0.jar            
		atmospheric-1.16.5-3.1.0.jar        
		majrusz-library-1.16.4-2.0.1.jar      
		curios-forge-1.16.5-4.0.5.2.jar       
		Atum-1.16.5-2.2.5.jar                 
		relics-0.2.3.1.jar                 
		savageandravage-1.16.5-3.1.0.jar      
		Patchouli-1.16.4-51.jar                 
		gravestone-1.16.5-1.0.5.jar         
		levelhearts-1.16.2-2.2.0.jar         
		StorageDrawers-1.16.3-8.2.2.jar     
		EndReborn+[0.8.4].jar                     
		BetterStrongholds-1.16.4-1.2.jar     
		majruszs-difficulty-1.16.4-1.1.0.jar      
		workshopsofdoom-1.16.4-1.1.0.1.jar     
		HunterIllager-1.16.5-1.3.1.jar            
		enhancedcelestials-1.0.4-1.16.4.jar
		FriendlyFire-1.16.5-7.0.2.jar      
		Disenchanting-forge-1.16.5-1.7.1.jar    
		BetterMineshafts-Forge-1.16.4-2.0.4.jar   
		geckolib-forge-1.16.5-3.0.41.jar         
**Additional Context:**
At the end, when I remove Infernal Expansion mod, everything is fine after that

**Comment by SwanX1** [comment] 2021-08-05 19:50
Duplicate of #196. Already fixed in the latest version.

**Closed as completed by SwanX1** 2021-08-05 19:50 UTC
Labels: bug, duplicate

**Comment by Jukabofy** [comment] 2021-08-05 22:46
sorry, I didn't notice
