### ISSUE TITLE
server doesn't boot (without crashreport)

### ISSUE THREAD

**Issue by koostcrashed** [nekomaster1000/Infernal-Expansion#326] opened 2022-01-25 01:26 UTC
### Describe the Bug

the server doesnt boot
https://pastebin.com/rTLRVD8k

### Reproduction Steps

run these mods on a server
crossroad 1.16.5-2.6.5
essential 1.16.5 2.11.1
infernal-expansion- 1.16.5-2.4.0
patchouli 1.16.4-53.2

### Expected Result

that boots up or at least give a crash log

### Operating System

Windows 10

### Mod Version

2.4.0

### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Other Mods

crossroad 1.16.5-2.6.5
essential 1.16.5 2.11.1
patchouli 1.16.4-53.2

**Comment by caelwarner** [comment] 2022-06-19 19:41
Duplicate of #309

**Closed as completed** 2022-06-29 17:34 UTC
Labels: bug, duplicate
