### ISSUE TITLE
Crash when trying to rejoin a world after leaving

### ISSUE THREAD

**Issue by InteJason** [nekomaster1000/Infernal-Expansion#274] opened 2021-08-30 11:36 UTC
When you leave a world and click on re-join, the game crashes. The crash report mentions infernal expansion.

https://pastebin.com/16d0THJV

**Comment by SwanX1** [comment] 2021-08-30 14:16
Duplicate of #258, fixed in commit 2b3fb682b9dc96f18492e7740a845fc99f34708e
<details>
<summary>Mentioned Users</summary>

 - @InteJason 
</details>

Please let me know if using this version of the mod doesn't fix your issue: [infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar](https://infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar)

**Comment by InteJason** [comment] 2021-08-31 10:57
tried it, did not fix it: https://pastebin.com/kYweiDnh

**Comment by SwanX1** [comment] 2021-08-31 11:18
Please post your world's level.dat file

**Comment by SwanX1** [comment] 2021-09-25 15:27
Closing due to no more information given.

**Closed as completed by SwanX1** 2021-09-25 15:27 UTC
Labels: bug, question, crash report
