### ISSUE TITLE
 "Errors in currently selected datapacks prevented world from loading" Error when trying to load Infernal Expansion

### ISSUE THREAD

**Issue by PhweeDev** [nekomaster1000/Infernal-Expansion#269] opened 2021-08-26 17:16 UTC
Hello,

I play with my own pack of mods. And I tried to add Infernal Expansion into the mix. (I play with 240 different mods) I get this log:

[Infernal Crash.txt](https://github.com/infernalexp/Infernal-Expansion/files/7061557/Infernal.Crash.txt)

I have no idea what is causing it. It's not just TerraForged, it's also just preventing me from creating a default world! DM me on Discord or simply reply to this is you have any idea what's causing this issue.

Thanks,
Phwee

**Comment by SwanX1** [comment] 2021-08-26 17:53
This is a duplicate of #258, if you want to get updates for this bug, subscribe to that issue.

**Closed as completed by SwanX1** 2021-08-26 17:53 UTC
Labels: bug, duplicate
