### ISSUE TITLE
The world does not load by creating a new world

### ISSUE THREAD

**Issue by omarkla** [nekomaster1000/Infernal-Expansion#260] opened 2021-08-13 05:48 UTC
**Describe the Bug:**
When creating a new world, the world freezes forever and does not finish loading, removing the mod solves the problem.

**How to Reproduce:**
By creating a new world

**Expected Behavior:**
That the mod loads like the others

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.66
 - Other mods that were running when the crash happened: A lot

**Additional Context:**
minecraft does not crash it just freezes forever so here is the log.
[latest.log](https://github.com/infernalexp/Infernal-Expansion/files/6980150/latest.log)

**Comment by caelwarner** [comment] 2021-08-13 06:02
This crash is caused by a spelling mistake in the recipe for vertical polished basalt slabs. The crash only occurs when Quark is loaded because vertical slabs are a Quark compatibility feature. The fix for this bug will be in the next update. Thanks

**Closed as completed** 2021-08-13 06:02 UTC
Labels: bug

**Comment by DKLYNTLY** [comment] 2021-08-21 15:40
when is the next update

**Comment by SwanX1** [comment] 2021-08-21 15:59
![so sorry sir](https://user-images.githubusercontent.com/36593309/130327740-aac54197-38c2-4ebb-b33d-b642d86d7424.png)

**Comment by Deepfriedyag** [comment] 2024-09-13 23:16
I still have this issue and am on the latest version of the mod for 1.16.5.
