### ISSUE TITLE
Glowstone Canyon Ruins Chests are Empty

### ISSUE THREAD

**Issue by TheRealZonko** [nekomaster1000/Infernal-Expansion#272] opened 2021-08-29 02:21 UTC
The loot tables in those little shacks in Infernal Expansion have no items inside

**Comment by SwanX1** [comment] 2021-08-30 09:39
![image](https://user-images.githubusercontent.com/36593309/131319774-0e1f2d50-0810-49c9-92e0-e4754b9c6a0d.png)
I couldn't reproduce.
Could you please send a seed and coordinates that demonstrate this issue?

**Comment by SwanX1** [comment] 2021-09-25 15:25
Closing this due to no more information given.

**Closed as completed by SwanX1** 2021-09-25 15:25 UTC
Labels: bug, question
