### ISSUE TITLE
No Turkish language support.

### ISSUE THREAD

**Issue by Jellyfen** [nekomaster1000/Infernal-Expansion#289] opened 2021-09-21 23:20 UTC
It doesn't have Turkish Language support. That occurs errors with "i,I" with "İ,i".
I can't use it on my game or server because of "glow_silk_moth" turns into "GLOW_SİLK_MOTH".

**Comment by SwanX1** [comment] 2021-09-24 07:57
Which version are you using?
Please use the template provided when creating an issue: [bug_report.md](https://github.com/infernalexp/Infernal-Expansion/blob/master-indev/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by Jellyfen** [comment] 2021-09-24 13:38
> Which version are you using?
> Please use the template provided when creating an issue: [bug_report.md](https://github.com/infernalexp/Infernal-Expansion/blob/master-indev/.github/ISSUE_TEMPLATE/bug_report.md)

I'm using 2.0.0. And im sorry about not using the right template. Its my first post.

**Comment by SwanX1** [comment] 2021-09-24 13:41
This is already fixed. (See commit fcbb3dfcea3f60e449ea4ee23233cffe4252aaf6)
Duplicate of #242

**Closed as completed by SwanX1** 2021-09-24 13:41 UTC
Labels: bug, duplicate
