### ISSUE TITLE
(1.18.2 Beta) Fungus caps and shroomloins generate too often

### ISSUE THREAD

**Issue by Looxond** [nekomaster1000/Infernal-Expansion#340] opened 2022-06-03 15:21 UTC
### Describe the Bug

Unlike previous versions fungus caps generate more than before, resulting in other mobs not being able to walk or spawn properly and tons of Shroomloins

### Reproduction Steps

1.  Go to crimson forest biome
2. Get swarmed by Shroomloins
3. Die

### Expected Result

When i go to the crimson forest i expect to find piglins and maybe a few hoglins and sometimes Shroomloin but not a whole colony of them

### Screenshots and Videos

![2022-06-02_11 01 29](https://user-images.githubusercontent.com/29359853/171882962-5815a68e-dfd9-4971-b698-04664120fccc.png)

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

**Comment by SwanX1** [comment] 2022-06-03 15:22
duplicate of #336, shroomloin spawn rates can be configured.

**Comment by SwanX1** [comment] 2022-06-03 15:22
also, next time split the issues into two seperate ones.

**Closed as completed by SwanX1** 2022-06-03 15:22 UTC
Labels: bug, duplicate
