### ISSUE TITLE
Error when joining server

### ISSUE THREAD

**Issue by squidgirll** [nekomaster1000/Infernal-Expansion#244] opened 2021-08-09 01:18 UTC
https://media.discordapp.net/attachments/865989442714861588/874096797474254879/unknown.png

**Comment by jaynesb** [comment] 2021-08-09 01:56
I'm seeing this as well in my own pack. It doesn't occur when Infernal Expansion is the only mod in the pack. No other mods in the pack produce this if Infernal Expansion is removed. Some sort of mod interaction I guess.
 - Infernal Expansion Version: 2.1.1
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2

Only occurs when connecting to a dedicated server, does not occur in singleplayer.
My pack's mod list: 
[modlist.txt](https://github.com/infernalexp/Infernal-Expansion/files/6951839/modlist.txt)

**Comment by squidgirll** [comment] 2021-08-09 02:00
yeah, singleplayer is working fine but when I connect to the server it gives this error

**Comment by Dariensg** [comment] 2021-08-09 02:06
This is a duplicate of issue #238. We've fixed it and the fix will be included in the next bug fix release which should be in a day or two! Sorry for the inconvenience!

**Closed as completed by Dariensg** 2021-08-09 02:06 UTC
Labels: bug, duplicate
